# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildJob
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'bharathi-sp-devops'
        subscriptionId: '23b03d6f-b164-4527-9acd-595d97060283'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'bharathi-cn-dep123'
        location: 'East US 2'
        templateLocation: 'URL of the file'
        csmFileLink: 'https://raw.githubusercontent.com/citrix/citrix-adc-azure-templates/master/templates/high_availability/availability_set/public_vip/3nic/mainTemplate.json'
        overrideParameters: '-adminUsername nsroot -adminPassword nsroot@123 -vnetNewOrExisting new'
        deploymentMode: 'Incremental'